let newVariable = 'S t r i n g';
let new1 = 'JavaScript';
console.log(newVariable)
console.log("This is the Output of toLocaleLowerCase :",newVariable.toLocaleLowerCase())
console.log("This is the Output of toLocaleUpperCase :",newVariable.toLocaleUpperCase())
console.log("This is the Output of toLowerCase :",newVariable.toLowerCase())
console.log("This is the Output of toUpperCase :",newVariable.toUpperCase())
console.log("This is the Output of slice :",newVariable.slice(2 ,7))
console.log("This is the Output of split :",newVariable.split(' '))
console.log("This is the Output of length :",newVariable.length)
console.log("This is the Output of includes :",newVariable.includes('p'))
console.log("This is the Output of indexOf :",newVariable.indexOf(2,7))
console.log("This is the Output of substring :",newVariable.substring(2,10))
console.log("This is the Output of substr :",newVariable.substr(2,7))
console.log("This is the Output of charAt :",newVariable.charAt(2))
console.log("This is the Output of concat :",newVariable.concat(new1))
console.log("This is the Output of endsWith :",newVariable.endsWith('n'))
console.log("This is the Output of startsWith :",newVariable.startsWith('S'))
console.log("This is the Output of trim :",newVariable.trim())
console.log("This is the Output of replace :",newVariable.replace('r','⚡'))
console.log("This is the Output of repeat :",newVariable.repeat(3))
console.log("This is the Output of search :",newVariable.search('r'))